<!-- Upcoming Events Calendar -->
<section class="mb-5">
    <div class="container">
        <h2 class="fw-bold mb-4">
            <i class="fas fa-calendar-alt text-primary me-2"></i>
            आगामी कार्यक्रमहरू
        </h2>

        <div class="row g-4">
            <!-- Calendar -->
            <div class="col-lg-6" data-aos="fade-right">
                <div class="calendar-card">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <button class="btn btn-sm btn-outline-primary" onclick="changeMonth(-1)">
                            <i class="fas fa-chevron-left"></i>
                        </button>
                        <h5 class="fw-bold mb-0" id="currentMonth">जनवरी २०२४</h5>
                        <button class="btn btn-sm btn-outline-primary" onclick="changeMonth(1)">
                            <i class="fas fa-chevron-right"></i>
                        </button>
                    </div>

                    <div class="row g-1 text-center mb-2">
                        <div class="col"><small class="text-muted fw-bold">आइत</small></div>
                        <div class="col"><small class="text-muted fw-bold">सोम</small></div>
                        <div class="col"><small class="text-muted fw-bold">मंगल</small></div>
                        <div class="col"><small class="text-muted fw-bold">बुध</small></div>
                        <div class="col"><small class="text-muted fw-bold">बिहि</small></div>
                        <div class="col"><small class="text-muted fw-bold">शुक्र</small></div>
                        <div class="col"><small class="text-muted fw-bold">शनि</small></div>
                    </div>

                    <div class="row g-1" id="calendarDays">
                        <!-- Calendar days will be generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- Events List -->
            <div class="col-lg-6" data-aos="fade-left">
                <div class="card shadow-sm h-100">
                    <div class="card-header bg-white">
                        <h6 class="mb-0 fw-bold">कार्यक्रम सूची</h6>
                    </div>
                    <div class="card-body">
                        <div id="eventsList">
                            @if(isset($events) && $events->count() > 0)
                                @foreach($events->take(5) as $event)
                                    <div class="d-flex align-items-start mb-3 pb-3 border-bottom">
                                        <div class="bg-primary text-white rounded p-2 me-3 text-center" style="min-width: 60px;">
                                            <small class="d-block">{{ \Carbon\Carbon::parse($event->date)->format('M') }}</small>
                                            <strong class="d-block fs-5">{{ \Carbon\Carbon::parse($event->date)->format('d') }}</strong>
                                        </div>
                                        <div class="flex-grow-1">
                                            <h6 class="fw-bold mb-1">{{ $event->title }}</h6>
                                            <p class="small text-muted mb-1">
                                                <i class="fas fa-clock me-1"></i> {{ $event->time ?? 'समय तोकिएको छैन' }}
                                            </p>
                                            <p class="small text-muted mb-0">
                                                <i class="fas fa-map-marker-alt me-1"></i> {{ $event->venue ?? 'स्थान तोकिएको छैन' }}
                                            </p>
                                            <span class="badge 
                                                @if($event->type === 'training') bg-primary 
                                                @elseif($event->type === 'interview') bg-warning 
                                                @elseif($event->type === 'orientation') bg-info 
                                                @elseif($event->type === 'certificate') bg-success 
                                                @else bg-secondary @endif mt-2">
                                                {{ $event->type ?? 'अन्य' }}
                                            </span>
                                        </div>
                                    </div>
                                @endforeach
                            @else
                                <div class="text-center py-4">
                                    <i class="fas fa-calendar-times fa-3x text-muted mb-3"></i>
                                    <p class="text-muted">हाल कुनै आगामी कार्यक्रम छैन।</p>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
let currentDate = new Date();
const eventDates = @json_encode($events->pluck('date')->toArray() ?? []);

function generateCalendar(date) {
    const year = date.getFullYear();
    const month = date.getMonth();
    
    const monthNames = ['जनवरी', 'फागुन', 'चैत', 'बैशाख', 'जेष्ठ', 'असार', 'श्रावण', 'भाद्र', 'असोज', 'कार्तिक', 'मंसिर', 'पुस', 'माघ'];
    document.getElementById('currentMonth').textContent = `${monthNames[month]} ${year}`;
    
    const firstDay = new Date(year, month, 1).getDay();
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    
    let calendarHTML = '';
    
    // Empty cells for days before the first day
    for (let i = 0; i < firstDay; i++) {
        calendarHTML += '<div class="col"></div>';
    }
    
    // Days of the month
    for (let day = 1; day <= daysInMonth; day++) {
        const dateString = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        const hasEvent = eventDates.includes(dateString);
        const isToday = day === new Date().getDate() && month === new Date().getMonth() && year === new Date().getFullYear();
        
        calendarHTML += `
            <div class="col">
                <div class="calendar-day ${hasEvent ? 'has-event' : ''} ${isToday ? 'active' : ''}" 
                     onclick="showEventsForDate('${dateString}')">
                    ${day}
                </div>
            </div>
        `;
    }
    
    document.getElementById('calendarDays').innerHTML = calendarHTML;
}

function changeMonth(delta) {
    currentDate.setMonth(currentDate.getMonth() + delta);
    generateCalendar(currentDate);
}

function showEventsForDate(dateString) {
    // Filter events for selected date
    const events = @json_encode($events->toArray() ?? []);
    const filteredEvents = events.filter(e => e.date === dateString);
    
    if (filteredEvents.length > 0) {
        let eventHTML = '<h6 class="fw-bold mb-3">' + dateString + ' का कार्यक्रमहरू</h6>';
        filteredEvents.forEach(event => {
            eventHTML += `
                <div class="d-flex align-items-start mb-3 pb-3 border-bottom">
                    <div class="bg-primary text-white rounded p-2 me-3 text-center" style="min-width: 60px;">
                        <small class="d-block">${event.type || 'अन्य'}</small>
                    </div>
                    <div>
                        <h6 class="fw-bold mb-1">${event.title}</h6>
                        <p class="small text-muted mb-0">${event.venue || 'स्थान तोकिएको छैन'}</p>
                    </div>
                </div>
            `;
        });
        document.getElementById('eventsList').innerHTML = eventHTML;
    }
}

// Initialize calendar
document.addEventListener('DOMContentLoaded', function() {
    generateCalendar(currentDate);
});
</script>
